### ISSUE TITLE
`vox help` crashes xonsh 0.18.2

### ISSUE THREAD

**Issue by ambv** [xonsh/xontrib-vox#11]
Like the title says. Other commands like `vox activate` and `vox new` work fine.

macOS Sonoma on M1 Max, xonsh installed from HomeBrew. xontrib-vox==0.0.1 installed with xpip today.

```
@ sys.version_info
sys.version_info(major=3, minor=12, micro=4, releaselevel='final', serial=0)
```

**Comment by ambv** [comment]
<img width="2032" alt="Screenshot 2024-07-24 at 14 40 05" src="https://github.com/user-attachments/assets/c9952476-1af1-4074-8523-78698097e37a">

**Comment by eugenesvk** [comment]
The help for help is correct — "show this help message and exit", —so it just exist the current shell :)

This bug happens on Windows as well

**Comment by yaxollum** [comment]
Fixed in https://github.com/xonsh/xonsh/pull/5698
